import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.72"

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // junit5
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.1")
}

application(Action {
    // Define the main class for the application.
    mainClassName = "com.yogadimas.AppKt"
})

// agar gradle mengenali junit5
// tasks.named<Test>("test") {
//     // useJUnit() default
//     useJUnitPlatform()
// }

// atau lebih singkat
tasks.test {
    useJUnitPlatform()
}

// secara default jvm 1.7 , sedangkan junit5 jalan di jvm 1.8 atau lebih tinggi
// tasks.withType(KotlinCompile::class).all{
//     kotlinOptions {
//         jvmTarget = "1.8"
//     }
// }

// atau lebih singkat
tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
}

// jalankan dengan perintah gradle test atau gradle test --info di terminal
