/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.yogadimas._0_app

import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Test


class AppTest {
    @Test
    fun testAppHasAGreeting() {

        println("ini testing")

        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
